api_platform:
    title: 'Ubitransport test API'
    description: 'A symfony API for a technique test in Ubitransport'
    version: '1.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
